export const Popup: string;
export const Popup__overlay: string;
export const Popup__overlay_opened: string;
export const fadeIn: string;
export const Popup__overlay_closed: string;
export const Popup__content: string;
export const Popup__content_opened: string;
export const zoomIn: string;
export const Popup__content_closed: string;
