name: Blog

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Building the app on remote server
        uses: appleboy/ssh-action@master
        env:
          GATSBY_GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          GATSBY_GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GATSBY_GITHUB_SERVER_URL,GATSBY_GITHUB_REPOSITORY,MAIL_HOST,MAIL_USER,MAIL_PASS,MAIL_RECIPIENT
          command_timeout: 20m
          script_stop: true
          script: |
            export GATSBY_GITHUB_SERVER_URL=$GATSBY_GITHUB_SERVER_URL
            export GATSBY_GITHUB_REPOSITORY=$GATSBY_GITHUB_REPOSITORY
            export MAIL_HOST=$MAIL_HOST
            export MAIL_USER=$MAIL_USER
            export MAIL_PASS=$MAIL_PASS
            export MAIL_RECIPIENT=$MAIL_RECIPIENT
            cd novavovikov.ru
            git reset --hard origin/master
            git pull
            docker-compose build
            docker-compose up --force-recreate -d
            docker system prune -f
